# Generated by Django 3.2.23 on 2025-01-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_success',
            field=models.BooleanField(default=False),
        ),
    ]
